package graph

import (
	"errors"
	"fmt"
	"sort"
	"time"

	"github.com/memor-dev/memor/internal/config"
	"github.com/memor-dev/memor/internal/store"
)

// Load reconstructs the graph from graph.snap plus any records appended to
// graph.log since the last compaction.
func Load(paths store.Paths) (*Graph, error) {
	g := New()

	snapRecords, err := ReadSnap(paths.Snap)
	if err != nil {
		return nil, fmt.Errorf("read snapshot: %w", err)
	}
	Apply(g, snapRecords)

	logRecords, _, err := ReadLog(paths.Log)
	if err != nil {
		return nil, fmt.Errorf("read log: %w", err)
	}
	Apply(g, logRecords)

	g.BuiltAt = latestTimestamp(g)
	return g, nil
}

func latestTimestamp(g *Graph) int64 {
	var newest int64
	for _, n := range g.nodes {
		if n.T > newest {
			newest = n.T
		}
	}
	return newest
}

// Write persists a graph as the canonical snapshot. It does not take the lock.
func Write(paths store.Paths, g *Graph) error {
	lines, err := Encode(Snapshot(g))
	if err != nil {
		return err
	}
	var data []byte
	for _, line := range lines {
		data = append(data, line...)
		data = append(data, '\n')
	}
	return store.WriteFileAtomic(paths.Snap, data)
}

// Compact folds graph.log into graph.snap, archives decayed memory nodes, and
// regenerates the rendered projection.
func Compact(paths store.Paths, cfg config.Config) (written, archived int, err error) {
	lock, err := store.AcquireLock(paths.Lock, store.CompactLockTimeout)
	if err != nil {
		return 0, 0, fmt.Errorf("lock state: %w", err)
	}
	defer lock.Release()

	return compactLocked(paths, cfg)
}

// compactLocked performs the compaction. Callers must already hold the state
// lock; nothing it calls acquires the lock itself, so it cannot self-deadlock.
func compactLocked(paths store.Paths, cfg config.Config) (written, archived int, err error) {
	// 1. PARSE — snapshot first, then the log so later records win.
	g := New()

	snapRecords, err := ReadSnap(paths.Snap)
	if err != nil {
		return 0, 0, fmt.Errorf("read snapshot: %w", err)
	}
	Apply(g, snapRecords)

	logRecords, consumed, err := ReadLog(paths.Log)
	if err != nil {
		return 0, 0, fmt.Errorf("read log: %w", err)
	}
	Apply(g, logRecords)

	// 2. DECAY — memory nodes only. Structural nodes are regenerated by
	// extraction, so archiving them would just churn the archive.
	evicted := evictMemory(g, cfg)

	// 3. COMMIT — archive before replacing the active snapshot so a failure
	// mid-write is retryable rather than lossy.
	if len(evicted) > 0 {
		lines, err := Encode(evicted)
		if err != nil {
			return 0, 0, err
		}
		if err := store.AppendArchive(paths.Archive, lines); err != nil {
			return 0, 0, fmt.Errorf("write archive: %w", err)
		}
	}
	if err := Write(paths, g); err != nil {
		return 0, 0, fmt.Errorf("write snapshot: %w", err)
	}
	if err := store.TruncatePrefix(paths.Log, consumed); err != nil {
		return 0, 0, fmt.Errorf("truncate log: %w", err)
	}

	// 4. PROJECT — graph.db is write-only output; a failure here must not fail
	// the compaction that already committed.
	_ = RenderToFile(paths.DB, g, cfg)

	return g.NodeCount(), len(evicted), nil
}

// AutoCompact compacts only once graph.log reaches the configured threshold.
// It writes nothing to stdout so callers on a stdio transport stay protocol-safe.
func AutoCompact(paths store.Paths, cfg config.Config) (written, archived int, ran bool, err error) {
	count, err := store.RecordCount(paths.Log)
	if err != nil {
		return 0, 0, false, fmt.Errorf("count log records: %w", err)
	}
	if count < cfg.Memory.LogMaxRecords {
		return 0, 0, false, nil
	}

	// Opportunistic: if someone else is compacting or writing, skip this round
	// rather than stalling the caller. The threshold will still be met next time.
	lock, err := store.AcquireLock(paths.Lock, 0)
	if errors.Is(err, store.ErrLockBusy) {
		return 0, 0, false, nil
	}
	if err != nil {
		return 0, 0, false, fmt.Errorf("lock state: %w", err)
	}
	defer lock.Release()

	written, archived, err = compactLocked(paths, cfg)
	if err != nil {
		return 0, 0, false, err
	}
	return written, archived, true, nil
}

// Rebuild replaces every machine-extracted node with a fresh pass, leaving
// agent-authored memories and their attachments untouched.
func Rebuild(paths store.Paths, cfg config.Config, nodes []*Node) (*Graph, error) {
	lock, err := store.AcquireLock(paths.Lock, store.CompactLockTimeout)
	if err != nil {
		return nil, fmt.Errorf("lock state: %w", err)
	}
	defer lock.Release()

	g := New()
	snapRecords, err := ReadSnap(paths.Snap)
	if err != nil {
		return nil, fmt.Errorf("read snapshot: %w", err)
	}
	Apply(g, snapRecords)

	logRecords, consumed, err := ReadLog(paths.Log)
	if err != nil {
		return nil, fmt.Errorf("read log: %w", err)
	}
	Apply(g, logRecords)

	g.PruneExtracted()
	for _, n := range nodes {
		g.AddNode(n)
	}
	g.BuiltAt = time.Now().Unix()

	if err := Write(paths, g); err != nil {
		return nil, fmt.Errorf("write snapshot: %w", err)
	}
	if err := store.TruncatePrefix(paths.Log, consumed); err != nil {
		return nil, fmt.Errorf("truncate log: %w", err)
	}
	if err := RenderToFile(paths.DB, g, cfg); err != nil {
		return nil, fmt.Errorf("render projection: %w", err)
	}

	return g, nil
}

// evictMemory archives memory nodes that decayed below the threshold or that
// overflow the node cap, and drops expired and superseded ones outright.
func evictMemory(g *Graph, cfg config.Config) []Record {
	type scored struct {
		node  *Node
		score float64
	}

	superseded := make(map[string]struct{})
	for _, n := range g.NodesOfKind(KindMem) {
		for _, id := range n.MetaList(MetaSupersedes) {
			superseded[id] = struct{}{}
		}
	}

	var keep []scored
	var evicted []Record

	for _, n := range g.NodesOfKind(KindMem) {
		if n.IsExpired() {
			g.RemoveNode(n.ID)
			evicted = append(evicted, NodeRecord(n))
			continue
		}
		if _, dead := superseded[n.ID]; dead {
			g.RemoveNode(n.ID)
			evicted = append(evicted, NodeRecord(n))
			continue
		}

		score := MemoryScore(g, n, cfg)
		if score < cfg.Memory.Decay.MinScore {
			g.RemoveNode(n.ID)
			evicted = append(evicted, NodeRecord(n))
			continue
		}
		keep = append(keep, scored{node: n, score: score})
	}

	if cfg.Memory.MaxMemoryNodes > 0 && len(keep) > cfg.Memory.MaxMemoryNodes {
		sort.Slice(keep, func(i, j int) bool {
			if keep[i].score != keep[j].score {
				return keep[i].score > keep[j].score
			}
			return keep[i].node.ID < keep[j].node.ID
		})
		for _, s := range keep[cfg.Memory.MaxMemoryNodes:] {
			g.RemoveNode(s.node.ID)
			evicted = append(evicted, NodeRecord(s.node))
		}
	}

	return evicted
}

// MemoryScore computes a memory node's retention score: subtype weight, decayed
// by age, boosted by how many other nodes it is attached to. A decision
// explaining three files outranks an isolated note of the same age.
func MemoryScore(g *Graph, n *Node, cfg config.Config) float64 {
	weight := cfg.TypeWeight(n.MemType())
	if n.Exp == -1 || n.MemType() == MemPreference {
		// Preferences are stated once and expected to hold indefinitely.
		return weight
	}

	decay := 1.0 / (1.0 + n.AgeDays()*cfg.Memory.Decay.Rate)

	links := 0
	for _, id := range n.MetaList(MetaExplains) {
		if _, ok := g.Node(id); ok {
			links++
		}
	}
	links += len(n.Tags())
	return weight * decay * (1.0 + float64(links)*0.1)
}
